#!/usr/bin/env python3


import gym
import gym_hectorquad
import rospy
import time
import subprocess
from gym_hectorquad.srv import Octomap

rospy.init_node('hectorquad_mapgen_node',anonymous=True)
subprocess.call('rosservice call /world/get_octomap',shell=True)
